controller_list:
  - name: "meca_arm_controller"
    action_ns: "follow_joint_trajectory"
    type: FollowJointTrajectory
    joints:
      - meca_axis_1_joint
      - meca_axis_2_joint
      - meca_axis_3_joint
      - meca_axis_4_joint
      - meca_axis_5_joint
      - meca_axis_6_joint
controller_list:
  - name: "Tool_planning_group_controller"
    action_ns: "follow_joint_trajectory"
    type: FollowJointTrajectory
    joints:
      - tcp_joint
