controller_list:
  - name: fake_meca_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - meca_axis_1_joint
      - meca_axis_2_joint
      - meca_axis_3_joint
      - meca_axis_4_joint
      - meca_axis_5_joint
      - meca_axis_6_joint
  - name: fake_Tool_planning_group_controller
    type: $(arg fake_execution_type)
    joints:
      - tcp_joint
initial:  # Define initial robot poses per group
  - group: meca_arm
    pose: Home
  - group: Tool_planning_group
    pose: with_Pipette